import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./variables.css";
import "./globals.css";
import { ThemeInit } from "@/components/theme-init"
import Script from "next/script";

const themeInit = `(function(){
  try {
    var raw = localStorage.getItem('app_theme');
    if (raw) {
      var s = JSON.parse(raw);
      if (s?.theme) document.documentElement.setAttribute('data-theme', s.theme);
      if (s?.scheme) document.documentElement.setAttribute('data-scheme', s.scheme);
    } else {
      // no saved theme -> default to yellow/light
      document.documentElement.setAttribute('data-theme', 'yellow');
      document.documentElement.setAttribute('data-scheme', 'light');
    }
  } catch (e) {
    // if anything goes wrong, still ensure default
    document.documentElement.setAttribute('data-theme', 'yellow');
    document.documentElement.setAttribute('data-scheme', 'light');
  }
})();`;




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <Script id="theme-init" strategy="beforeInteractive">
          {themeInit}
        </Script>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-hidden bg-[var(--background)] text-foreground`}>
        {children}
      </body>
    </html>
  );
}

